modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/SamsTheNerd/ducky-periphs/issues"
showAsResourcePack = false

[[mods]]
modId = "duckyperiphs"
version = "${mod_version}"
displayName = "Ducky Peripherals"
displayURL = "https://github.com/SamsTheNerd/ducky-periphs"
logoFile = "DuckyPeriphsIconLargeCommon.png"
authors = "samsthenerd"
description = "Adds a variety of peripheral addons for ComputerCraft Tweaked"

[[dependencies.duckyperiphs]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.duckyperiphs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.duckyperiphs]]
    modId="architectury"
    mandatory=true
    versionRange="[9.1.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.duckyperiphs]]
    modId="computercraft"
    mandatory=true
    versionRange="[1.106.1,)"
    ordering="NONE"
    side="BOTH"